version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    image: postgres:16-alpine
    container_name: stravanalytics-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stravanalytics
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data